# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build-prod

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@master
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Stage - get maven version
      run: mvn --version
    - name: Stage - execute test project
      run: mvn test
    - name: Stage - execute clean project
      run: mvn clean 
    - name: Stage - build project
      run: mvn -B package --file pom.xml
    - name: Stage - generate jar file
      run: mvn package
    - name: deploy - build and push to docker hub
      uses: docker/build-push-action@master 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
    
